-- init.sql
CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    difficulty INT DEFAULT 1,      -- Task difficulty scaling weight
    allocated_hours FLOAT DEFAULT 0.0, -- Output generated by the Zenith optimization
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed with initial example tasks matching the algorithm article
INSERT INTO tasks (title, difficulty) VALUES 
('Work on Essay', 2),
('Math Homework', 1),
('Edit Video', 5),
('Study Physics Exam', 4);