/**
 * Measurements behind MATH.md §8.9's recovery-rate calibration numbers — the
 * ones that justify `RECOVERY_PRIOR_STRENGTH = 0.05` and describe what the fit
 * can and cannot see. None of them had a committed sweep behind them:
 *
 *   - the λ calibration profile: one consistent logged rest moves r 51% of the
 *     way to what it implies, three 72%, ten 88%; λ = 0.1 "sat at 37%" for the
 *     first log and λ = 0.25 (the §8.7 value) would be worse still;
 *   - the fit's lever arm dD/dr ≈ 0.2–0.4 for 30–60 min breaks from half
 *     drain, "roughly half the drain fit's";
 *   - noiseless 8-log recovery across the range: 0.3 → 0.307, 0.7 → 0.700,
 *     1.0 → 0.976, 1.5 → 1.365, and the high-r shrinkage 2.5 → ~1.81 from
 *     36-min breaks because any r ≥ 2 leaves less than one rating notch of
 *     residual drain;
 *   - short breaks carry the high-r signal (2.5 reads 2.0 from 15-min pairs
 *     against 1.58 from 1h pairs);
 *   - quantization + ±1-notch jitter stays "within ~0.05 of truth";
 *   - the motivating α bias: true α = 0.5 under true r = 1.4 fits to 0.415 at
 *     the default r, and to 0.469 conditioned on r fitted from 5 rests;
 *   - and §8.7's ν₀ ≠ λ note, which quotes reported ± half-widths on two r-fit
 *     populations it names but never sized here: the §8.9 tests' 6-observation
 *     pair set and their adversarial-pairs fixture, each reported under the
 *     shipped noise floor ν₀ = 4 and under the pre-fix ν₀ = λ it replaced. The
 *     move is a blend toward σ₀, not a floor under the ±: it widens the clean
 *     small-n sets several-fold and TIGHTENS the adversarial pairs, whose
 *     residuals are far noisier than σ₀ = 0.21. Both fixtures are COPIED from
 *     `zenith-energy.test.ts` (the generator at "One logged rest = mind +
 *     body", and the "adversarial pairs" case), not re-invented — a different
 *     fixture answers a different question, which is how the ± 0.249 that used
 *     to stand here became unreproducible.
 *
 * A probe, not a test: every number moves when the reservoir law, the ridge or
 * the defaults move — legitimately. The suite pins only the direction (see
 * "recovery-rate calibration (fitRecoveryRate, MATH.md §8.9)" in
 * `zenith-energy.test.ts`).
 *
 * FIXTURE. §8.9's own numbers never named their fixture, so this uses the
 * suite's: one logged rest = a mind pair (drained 0.6 going in) and a body pair
 * (0.45), break lengths cycling 0.5/0.75/1/0.5/0.75/0.5/1/0.75 h, drained-after
 * generated by the rest law itself at the true r.
 *
 * λ ≠ RECOVERY_PRIOR_STRENGTH is not reachable through `fitRecoveryRate`, so
 * the ridge is rebuilt here (`fitAtLambda`, the shipped minimizer included) and
 * VALIDATED against the shipped fit at the shipped λ before any λ = 0.1 / 0.25
 * number is believed — a nonzero worst gap invalidates those two rows. ν₀ is
 * not reachable either, so the posterior std is rebuilt the same way
 * (`stdAtNu0`) and validated the same way at the shipped ν₀ before any pre-fix
 * ± is believed.
 *
 * Usage: npm run probe
 */

import { describe, expect, it } from 'vitest';
import {
	CALIBRATION_NOISE_PRIOR_WEIGHT,
	DEFAULT_ENERGY_PARAMS,
	fitDrainRate,
	fitRecoveryRate,
	RECOVERY_FIT_MAX,
	RECOVERY_FIT_MIN,
	RECOVERY_NOISE_PRIOR_STD,
	RECOVERY_PRIOR_STRENGTH,
	type RestObservation,
} from '$lib/business/model/zenith-energy';

/** Seeded so a quoted number can be reproduced, not just re-rolled. */
function mulberry32(seed: number): () => number {
	let a = seed;

	return () => {
		a = (a + 0x6d2b79f5) | 0;
		let t = Math.imul(a ^ (a >>> 15), 1 | a);
		t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;

		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}

const M = DEFAULT_ENERGY_PARAMS.restRecoveryMultiplier;
const PRIOR = DEFAULT_ENERGY_PARAMS.recoveryRate;
const BREAKS = [0.5, 0.75, 1, 0.5, 0.75, 0.5, 1, 0.75];

const pair = (rate: number, before: number, hours: number): RestObservation => ({
	drainedBefore: before,
	drainedAfter: before * Math.exp(-rate * M * hours),
	hours,
});

/** `count` logged rests, each contributing a mind and a body observation. */
const loggedRests = (rate: number, count: number, hours?: number): RestObservation[] =>
	Array.from(
		{
			length: count,
		},
		(_, i) => {
			const g = hours ?? BREAKS[i % BREAKS.length];

			return [pair(rate, 0.6, g), pair(rate, 0.45, g)];
		},
	).flat();

/** The shipped `minimizeSmooth1D`, rebuilt: it is internal. */
function minimize(f: (x: number) => number, min: number, max: number): number {
	const GRID = 128;
	let bestIdx = 0;
	let bestVal = Infinity;

	for (let i = 0; i <= GRID; i++) {
		const val = f(min + ((max - min) * i) / GRID);

		if (val < bestVal) {
			bestVal = val;
			bestIdx = i;
		}
	}

	const cell = (max - min) / GRID;
	let lo = Math.max(min, min + (bestIdx - 1) * cell);
	let hi = Math.min(max, min + (bestIdx + 1) * cell);
	const INV_PHI = (Math.sqrt(5) - 1) / 2;
	let x1 = hi - INV_PHI * (hi - lo);
	let x2 = lo + INV_PHI * (hi - lo);
	let f1 = f(x1);
	let f2 = f(x2);

	for (let i = 0; i < 48; i++) {
		if (f1 < f2) {
			hi = x2;
			x2 = x1;
			f2 = f1;
			x1 = hi - INV_PHI * (hi - lo);
			f1 = f(x1);
		} else {
			lo = x1;
			x1 = x2;
			f1 = f2;
			x2 = lo + INV_PHI * (hi - lo);
			f2 = f(x2);
		}
	}

	return (lo + hi) / 2;
}

/** `fitRecoveryRate`'s ridge with λ exposed (the only reason this exists). */
function fitAtLambda(observations: RestObservation[], lambda: number): number {
	const used = observations.filter((o) => o.drainedBefore > 0 && o.hours > 0);

	if (used.length === 0) return PRIOR;

	const objective = (r: number): number => {
		let sum = lambda * (r - PRIOR) * (r - PRIOR);

		for (const o of used) {
			const resid = o.drainedAfter - o.drainedBefore * Math.exp(-r * M * o.hours);
			sum += resid * resid;
		}

		return sum;
	};

	return minimize(objective, RECOVERY_FIT_MIN, RECOVERY_FIT_MAX);
}

/**
 * `fitRecoveryRate`'s reported ± with ν₀ exposed: σ̂² = (ν₀σ₀² + SSR)/(ν₀ + n)
 * blended at `rate`, then the Laplace curvature √(σ̂²/(Σ(dD/dr)² + λ)). The
 * shipped fit hard-wires ν₀ = CALIBRATION_NOISE_PRIOR_WEIGHT, so the pre-fix
 * ν₀ = λ posterior it replaced is only reachable here.
 */
function stdAtNu0(observations: RestObservation[], rate: number, nu0: number): number {
	const used = observations.filter((o) => o.drainedBefore > 0 && o.hours > 0);
	const predict = (r: number, o: RestObservation) => o.drainedBefore * Math.exp(-r * M * o.hours);
	const h = 1e-4;
	let ssr = 0;
	let sensitivity = 0;

	for (const o of used) {
		const resid = o.drainedAfter - predict(rate, o);
		ssr += resid * resid;
		const dD = (predict(rate + h, o) - predict(rate - h, o)) / (2 * h);
		sensitivity += dD * dD;
	}

	const sigma2 =
		(nu0 * RECOVERY_NOISE_PRIOR_STD * RECOVERY_NOISE_PRIOR_STD + ssr) / (nu0 + used.length);

	return Math.sqrt(sigma2 / (sensitivity + RECOVERY_PRIOR_STRENGTH));
}

/** The §8.9 suite's "adversarial pairs (more drained after resting)" fixture. */
const ADVERSARIAL_PAIRS: RestObservation[] = [
	{
		drainedBefore: 0.3,
		drainedAfter: 0.6,
		hours: 0.5,
	},
	{
		drainedBefore: 0.4,
		drainedAfter: 0.7,
		hours: 0.5,
	},
];

const f3 = (x: number) => x.toFixed(3);
const pct = (x: number) => `${(100 * x).toFixed(0)}%`;

describe('recovery-rate calibration', () => {
	it('validates the λ- and ν₀-exposed replicas against the shipped fit', () => {
		const random = mulberry32(20260806);
		let worst = 0;
		let worstStd = 0;

		for (let day = 0; day < 200; day++) {
			const obs = Array.from(
				{
					length: 1 + Math.floor(random() * 8),
				},
				() => ({
					drainedBefore: random(),
					drainedAfter: random(),
					hours: random() * 1.5,
				}),
			);

			const shipped = fitRecoveryRate(obs, PRIOR, {
				restRecoveryMultiplier: M,
			});

			if (!shipped.fitted) continue;

			worst = Math.max(worst, Math.abs(shipped.rate - fitAtLambda(obs, RECOVERY_PRIOR_STRENGTH)));

			worstStd = Math.max(
				worstStd,
				Math.abs(shipped.rateStd! - stdAtNu0(obs, shipped.rate, CALIBRATION_NOISE_PRIOR_WEIGHT)),
			);
		}

		console.log(
			`[§8.9 replica] 200 random observation sets: worst |replica − fitRecoveryRate| = ${worst.toExponential(3)}, worst |std replica − rateStd| at the shipped ν₀ = ${worstStd.toExponential(3)}`,
		);

		// Validity gate, not a moving number: the λ = 0.1 / 0.25 rows below are
		// only meaningful if the replica IS the shipped ridge at the shipped λ.
		// The tolerance is the shared minimizer's own convergence, not slack.
		expect(worst).toBeLessThan(1e-6);

		// Same gate for the ν₀ replica: at the shipped ν₀ it is the shipped
		// formula on the shipped MAP, so only float arithmetic may differ — a
		// wider gap invalidates every pre-fix ± below.
		expect(worstStd).toBeLessThan(1e-12);
	});

	it('measures the λ calibration profile (MATH.md §8.9)', () => {
		const TRUE_R = 1.4;

		for (const lambda of [RECOVERY_PRIOR_STRENGTH, 0.1, 0.25]) {
			const moved = [1, 3, 10].map((count) => {
				const rate = fitAtLambda(loggedRests(TRUE_R, count), lambda);

				return (rate - PRIOR) / (TRUE_R - PRIOR);
			});

			console.log(
				`[§8.9 profile] λ = ${lambda}${lambda === RECOVERY_PRIOR_STRENGTH ? ' (shipped)' : ''}: true r 1.4 from the prior 0.7 — 1 rest moves ${pct(moved[0])}, 3 ${pct(moved[1])}, 10 ${pct(moved[2])} of the way`,
			);
		}
	});

	it('measures the fit lever arm dD/dr against the drain fit dD/dα', () => {
		const dDdr = (g: number, dPre: number) => M * g * dPre * Math.exp(-PRIOR * M * g);

		console.log(
			`[§8.9 lever] dD/dr from half drain: 30 min ${f3(dDdr(0.5, 0.5))}, 45 min ${f3(dDdr(0.75, 0.5))}, 60 min ${f3(dDdr(1, 0.5))} (MATH.md now says 0.22–0.26 against dD/dα 0.6–0.9)`,
		);

		// The drain law's own sensitivity, for the "roughly half" comparison:
		// d = 1 − (C_eq + (1 − C_eq)·e^(−ρh)), ρ = α·w + r·m·gate.
		const drained = (alpha: number, w: number, hours: number) => {
			const rec = PRIOR * M;
			const gate = 1 - (1 - DEFAULT_ENERGY_PARAMS.microRecoveryFraction) * w;
			const rho = alpha * w + rec * gate;
			const eq = (rec * gate) / rho;

			return 1 - (eq + (1 - eq) * Math.exp(-rho * hours));
		};

		const dDda = (w: number, hours: number) => {
			const h = 1e-4;
			const a = DEFAULT_ENERGY_PARAMS.alphaCog;

			return (drained(a + h, w, hours) - drained(a - h, w, hours)) / (2 * h);
		};

		console.log(
			`[§8.9 lever] dD/dα at α₀, demand 0.9: 1 h ${f3(dDda(0.9, 1))}, 2 h ${f3(dDda(0.9, 2))}, 3 h ${f3(dDda(0.9, 3))}`,
		);
	});

	it('measures noiseless recovery across the range and the high-r shrinkage', () => {
		for (const trueR of [0.3, 0.7, 1.0, 1.5, 2.0, 2.5]) {
			const fit = fitRecoveryRate(loggedRests(trueR, 8), PRIOR, {
				restRecoveryMultiplier: M,
			});

			console.log(
				`[§8.9 range] 8 noiseless logs, true r ${trueR} → ${f3(fit.rate)} ± ${f3(fit.rateStd!)}`,
			);
		}

		// "36-min breaks": one break length for every pair, not the cycling set.
		for (const g of [0.25, 0.6, 1]) {
			const fit = fitRecoveryRate(loggedRests(2.5, 8, g), PRIOR, {
				restRecoveryMultiplier: M,
			});

			console.log(
				`[§8.9 range] 8 noiseless logs of ${Math.round(60 * g)}-min breaks, true r 2.5 → ${f3(fit.rate)} ± ${f3(fit.rateStd!)}`,
			);
		}

		// Why high r saturates: the residual drain after the break, against one
		// 0–10 rating notch (0.1 of the drained fraction).
		for (const r of [1.5, 2, 2.5, 3]) {
			const residual = 0.6 * Math.exp(-r * M * 0.6);

			console.log(
				`[§8.9 notch] r = ${r}: 36-min break from drained 0.6 leaves ${f3(residual)} — ${residual < 0.1 ? 'below' : 'above'} one rating notch`,
			);
		}
	});

	it('measures the fit under 0–10 notch quantization plus ±1-notch jitter', () => {
		const random = mulberry32(89);
		const notch = (x: number) => Math.max(0, Math.min(1, Math.round(x * 10) / 10));

		for (const trueR of [0.3, 0.7, 1.0, 1.5, 2.5]) {
			const clean = fitRecoveryRate(loggedRests(trueR, 8), PRIOR, {
				restRecoveryMultiplier: M,
			}).rate;

			let worstFromTruth = 0;
			let worstFromClean = 0;
			const fromTruth: number[] = [];

			for (let trial = 0; trial < 200; trial++) {
				const noisy = loggedRests(trueR, 8).map((o) => ({
					...o,
					drainedBefore: notch(o.drainedBefore + 0.1 * (Math.floor(3 * random()) - 1)),
					drainedAfter: notch(o.drainedAfter + 0.1 * (Math.floor(3 * random()) - 1)),
				}));

				const rate = fitRecoveryRate(noisy, PRIOR, {
					restRecoveryMultiplier: M,
				}).rate;

				worstFromTruth = Math.max(worstFromTruth, Math.abs(rate - trueR));
				worstFromClean = Math.max(worstFromClean, Math.abs(rate - clean));
				fromTruth.push(Math.abs(rate - trueR));
			}

			fromTruth.sort((a, b) => a - b);

			console.log(
				`[§8.9 jitter] true r ${trueR}, 200 seeded ±1-notch trials: |fit − truth| median ${f3(fromTruth[100])} p90 ${f3(fromTruth[180])} worst ${f3(worstFromTruth)}; worst |fit − noiseless fit| ${f3(worstFromClean)}`,
			);
		}
	});

	it('measures what the ν₀ ≠ λ noise floor did to the reported ± (MATH.md §8.7)', () => {
		// The populations §8.7's ν₀ note names, sized side by side in one run:
		// the §8.9 tests' 6-observation pair set (three logged rests, mind + body
		// each — the count its λ profile's "3 rests" row fits), at the prior and
		// at the true r = 1.4 that profile drives, and their adversarial-pairs
		// fixture. Clean small-n first, then high scatter.
		const populations: [string, RestObservation[]][] = [
			['6 clean rest pairs (3 logged rests), true r = the prior 0.7', loggedRests(PRIOR, 3)],
			['6 clean rest pairs (3 logged rests), true r 1.4', loggedRests(1.4, 3)],
			['adversarial pairs (more drained after resting)', ADVERSARIAL_PAIRS],
		];

		// ν₀ → ∞ leaves σ̂² = σ₀² exactly: the ± σ₀ alone would report, which is
		// what the ν₀ = 4 blend is pulling toward.
		const FLOOR_ONLY = 1e9;

		for (const [label, obs] of populations) {
			const fit = fitRecoveryRate(obs, PRIOR, {
				restRecoveryMultiplier: M,
			});

			const preFix = stdAtNu0(obs, fit.rate, RECOVERY_PRIOR_STRENGTH);
			const floorOnly = stdAtNu0(obs, fit.rate, FLOOR_ONLY);

			console.log(
				`[§8.7 floor] ${label}, n = ${fit.usedCount}: r ${f3(fit.rate)} ± ${f3(fit.rateStd!)} at the shipped ν₀ = ${CALIBRATION_NOISE_PRIOR_WEIGHT}, ± ${f3(preFix)} under the pre-fix ν₀ = λ = ${RECOVERY_PRIOR_STRENGTH} = ${(fit.rateStd! / preFix).toFixed(1)}× the pre-fix ±, against ± ${f3(floorOnly)} from the σ₀ = ${RECOVERY_NOISE_PRIOR_STD} floor alone`,
			);

			// The invariant, not the magnitudes, and it is two-sided: ν₀
			// pseudo-observations move σ̂² toward σ₀², so raising ν₀ from λ to 4
			// widens data that looks cleaner than σ₀ and TIGHTENS data that looks
			// noisier. Both moves are steps toward the floor-only ±, never past it.
			expect(Math.sign(fit.rateStd! - preFix)).toBe(Math.sign(floorOnly - preFix));
			expect(Math.abs(fit.rateStd! - preFix)).toBeLessThan(Math.abs(floorOnly - preFix));
		}

		// Construction: these ARE the named populations — six observations for
		// the pair sets, and pairs that really do rest backwards for the other.
		expect(populations[0][1]).toHaveLength(6);
		expect(populations[1][1]).toHaveLength(6);
		expect(ADVERSARIAL_PAIRS.every((o) => o.drainedAfter > o.drainedBefore)).toBe(true);
	});

	it('measures the α bias the r fit was built to remove', () => {
		const TRUE_R = 1.4;
		const TRUE_ALPHA = 0.5;

		const drainAt = (recovery: number, w: number, hours: number) => {
			const rec = recovery * M;
			const gate = 1 - (1 - DEFAULT_ENERGY_PARAMS.microRecoveryFraction) * w;
			const rho = TRUE_ALPHA * w + rec * gate;
			const eq = (rec * gate) / rho;

			return 1 - (eq + (1 - eq) * Math.exp(-rho * hours));
		};

		const drainObs = [1.5, 2, 2.5, 2, 1.5].map((hours) => ({
			demand: 0.9,
			hours,
			drainedFraction: drainAt(TRUE_R, 0.9, hours),
		}));

		const lawParams = (recovery: number) => ({
			recoveryRate: recovery,
			restRecoveryMultiplier: M,
			microRecoveryFraction: DEFAULT_ENERGY_PARAMS.microRecoveryFraction,
		});

		const biased = fitDrainRate(drainObs, DEFAULT_ENERGY_PARAMS.alphaCog, lawParams(PRIOR));

		console.log(
			`[§8.9 chain] true α 0.5 under true r 1.4, fitted at the default r ${PRIOR}: α → ${f3(biased.alpha)} (bias ${f3(Math.abs(biased.alpha - TRUE_ALPHA))})`,
		);

		for (const count of [1, 3, 5, 10]) {
			const rFit = fitRecoveryRate(loggedRests(TRUE_R, count), PRIOR, {
				restRecoveryMultiplier: M,
			});

			const conditioned = fitDrainRate(
				drainObs,
				DEFAULT_ENERGY_PARAMS.alphaCog,
				lawParams(rFit.rate),
			);

			console.log(
				`[§8.9 chain] ${count} logged rests → r ${f3(rFit.rate)}, α conditioned on it ${f3(conditioned.alpha)} (bias ${f3(Math.abs(conditioned.alpha - TRUE_ALPHA))})`,
			);
		}
	});
});
