/**
 * Measurements behind MATH.md §8.10's two unbacked feasibility claims:
 *
 *   - "Only λ₀ is identifiable": sweeping V_T (`terminalEnergyValue`) over
 *     [0, 6] in 12 steps moved the optimal stop across just two 45-min lattice
 *     levels, and the joint (λ₀, V_T) response surface is almost constant in
 *     V_T — the reason the fit targets λ₀ alone and conditions on V_T.
 *   - the chosen reconstruction's brackets contain the true λ₀ across the probe
 *     grid (true 0.5 → [0.49, 0.78], 0.9 → [0.85, 1.18], 1.3 → [1.16, 1.48]),
 *     with midpoints tracking truth within ~0.13.
 *
 * A probe, not a test. The bracket midpoint is read through the shipped
 * `stopIndifferencePoint`; the day is generated by the optimizer at the true λ₀,
 * exactly as the suite's §8.10 fixtures do.
 *
 * Whatever it prints belongs in MATH.md WITH ITS DATE, beside the claim it
 * supports.
 *
 * Usage: npm run probe
 */

import { describe, it } from 'vitest';
import {
	DEFAULT_ENERGY_PARAMS,
	DEFAULT_STEP_HOURS,
	optimizeSchedule,
	stopIndifferencePoint,
	type EnergyTaskInput,
	type StopObservation,
} from '$lib/business/model/zenith-energy';

const task = (
	id: number,
	difficulty: number,
	enjoyment: number,
	cognitiveDemand: number,
	physicalDemand: number,
): EnergyTaskInput => ({
	id,
	title: `t${id}`,
	difficulty,
	enjoyment,
	cognitiveDemand,
	physicalDemand,
});

/** The standard probe day (boxing / guitar / reading). */
const DAY: EnergyTaskInput[] = [
	task(1, 10, 10, 0.2, 1.0),
	task(2, 6, 9, 0.4, 0.3),
	task(3, 4, 7, 0.5, 0.05),
];

const worked = (freeTimeValue: number, terminalEnergyValue: number, windowHours: number) =>
	optimizeSchedule(DAY, windowHours, {
		...DEFAULT_ENERGY_PARAMS,
		freeTimeValue,
		terminalEnergyValue,
	}).blocks.reduce((sum, b) => (b.taskId === null ? sum : sum + b.hours), 0);

describe('stopping-value identifiability', () => {
	it('sweeps V_T against λ₀ for the optimal stop (MATH.md §8.10 feasibility 2)', () => {
		const V_T = Array.from(
			{
				length: 13,
			},
			(_, i) => i * 0.5,
		);

		for (const windowHours of [8, 12]) {
			for (const lambda of [0.3, 0.5, 0.9, 1.3]) {
				const hours = V_T.map((vt) => worked(lambda, vt, windowHours));
				const levels = new Set(hours).size;

				console.log(
					`[§8.10 V_T] ${windowHours}h window, λ₀ ${lambda}: worked hours over V_T 0→6 ${hours.join('/')} — ${levels} distinct lattice level(s), span ${((Math.max(...hours) - Math.min(...hours)) / DEFAULT_STEP_HOURS).toFixed(0)} step(s)`,
				);
			}
		}
	});

	it('tracks the true λ₀ through the bracket midpoint (MATH.md §8.10 reconstruction)', () => {
		for (const lambda of [0.5, 0.9, 1.3]) {
			const rows = [8, 10, 12].map((windowHours) => {
				const { blocks } = optimizeSchedule(DAY, windowHours, {
					...DEFAULT_ENERGY_PARAMS,
					freeTimeValue: lambda,
				});

				const byTask = new Map<number, number>();

				for (const b of blocks) {
					if (b.taskId !== null) byTask.set(b.taskId, (byTask.get(b.taskId) ?? 0) + b.hours);
				}

				const observation: StopObservation = {
					tasks: DAY,
					windowHours,
					workedHours: [...byTask].map(([taskId, hours]) => ({
						taskId,
						hours,
					})),
				};

				const mid = stopIndifferencePoint(observation, DEFAULT_ENERGY_PARAMS);

				return `${windowHours}h ${mid === null ? 'censored' : mid.toFixed(3)}`;
			});

			console.log(`[§8.10 midpoint] true λ₀ ${lambda}: ${rows.join(', ')}`);
		}
	});
});
