/**
 * Measurements behind MATH.md §8.10's two unbacked feasibility claims:
 *
 *   - "Only λ₀ is identifiable": sweeping V_T (`terminalEnergyValue`) over
 *     [0, 6] in 12 steps moved the optimal stop across just two 45-min lattice
 *     levels, and the joint (λ₀, V_T) response surface is almost constant in
 *     V_T — the reason the fit targets λ₀ alone and conditions on V_T.
 *   - the chosen reconstruction's brackets contain the true λ₀ across the probe
 *     grid (true 0.5 → [0.49, 0.78], 0.9 → [0.85, 1.18], 1.3 → [1.16, 1.48]),
 *     with midpoints tracking truth within ~0.13.
 *
 * A probe, not a test. The bracket midpoint is read through the shipped
 * `stopIndifferencePoint`; the day is generated by the optimizer at the true λ₀,
 * exactly as the suite's §8.10 fixtures do.
 *
 * The midpoint arm reads the SAME day twice, and the pair is the measurement
 * (2026-08-19): once with the plan's sessions logged as they finished, so their
 * log moments carry the day's breaks, and once with them summed per task, which
 * is what the reconstruction did before it read the moments. The second reading
 * is the falsified ~0.13 contract; the first is what replaced it.
 *
 * Added 2026-08-24: what a mis-set V_T costs the FIT, and whether the posterior
 * std beside it can tell. The two arms above price V_T in worked hours; this
 * one prices it in λ₀, which is the unit §8.10 reports in. It is the same
 * conditioning error read at the estimator instead of at the optimum, and the
 * point of it is the RATIO: every day of a history shares the slider, so the
 * error is common-mode and the i.i.d.-days posterior std cannot see it.
 *
 * Added 2026-08-21: the V_T sweep over SEEDED DAYS, not one. Aligning this
 * probe's day onto the sliders (ROADMAP M44) deleted both witnesses §8.10 cited
 * for "V_T is not free" — the 3-step move at 8 h / λ₀ 1.3 and the three-level
 * walk at 12 h / λ₀ 0.9 were properties of demands no slider can produce, and on
 * the reachable day every cell moves at most one step. One day cannot settle
 * which reading is typical, and quoting one day is what put a retracted claim
 * and then its retraction into this section, so the arm below sweeps V_T across
 * seeded days and reports the DISTRIBUTION of the span.
 *
 * Usage: npm run probe
 */

import { describe, it } from 'vitest';
import {
	DEFAULT_ENERGY_PARAMS,
	DEFAULT_STEP_HOURS,
	fitStoppingValue,
	optimizeSchedule,
	stopIndifferencePoint,
	type EnergyTaskInput,
	type ScheduleBlock,
	type StopObservation,
} from '$lib/business/model/zenith-energy';

const task = (
	id: number,
	difficulty: number,
	enjoyment: number,
	cognitiveDemand: number,
	physicalDemand: number,
): EnergyTaskInput => ({
	id,
	title: `t${id}`,
	difficulty,
	enjoyment,
	cognitiveDemand,
	physicalDemand,
});

/**
 * The standard probe day (boxing / guitar / reading).
 * Aligned 2026-08-21 (ROADMAP M44): guitar 0.4/0.3 → 0.6/0 and reading
 * 0.5/0.05 → 0.4/0, the demands the three integer sliders actually reach at the
 * difficulties this day is stated in.
 */
const DAY: EnergyTaskInput[] = [
	task(1, 10, 10, 0.2, 1.0),
	task(2, 6, 9, 0.6, 0),
	task(3, 4, 7, 0.4, 0),
];

const ORIGIN = Date.parse('2026-08-19T08:00:00.000Z');

/**
 * The plan as the 🪫 log would hold it: one row per contiguous session, each
 * carrying the wall-clock moment it ended, so the breaks between them are
 * recoverable exactly as `readFinishedDays` recovers them from `createdAt`.
 */
function sessionRows(blocks: ScheduleBlock[]): StopObservation['workedHours'] {
	const rows: StopObservation['workedHours'] = [];
	let clock = 0;

	for (const b of blocks) {
		clock += b.hours;

		if (b.taskId !== null)
			rows.push({
				taskId: b.taskId,
				hours: b.hours,
				endedAt: ORIGIN + clock * 3_600_000,
			});
	}

	return rows;
}

function mulberry32(seed: number): () => number {
	let a = seed;

	return () => {
		a = (a + 0x6d2b79f5) | 0;
		let t = Math.imul(a ^ (a >>> 15), 1 | a);
		t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;

		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}

/** Slider-reachable by construction: demands are tenths, difficulty is Eᵤ. */
function seededDay(rnd: () => number): EnergyTaskInput[] {
	return Array.from(
		{
			length: 2 + Math.floor(rnd() * 3),
		},
		(_, i) => {
			const mental = Math.floor(rnd() * 11);
			const physical = Math.floor(rnd() * 11);

			return task(
				i + 1,
				Math.min(10, Math.max(1, Math.max(mental, physical) + 0.3 * Math.min(mental, physical))),
				1 + Math.floor(rnd() * 10),
				mental / 10,
				physical / 10,
			);
		},
	);
}

const workedOn = (
	tasks: EnergyTaskInput[],
	freeTimeValue: number,
	terminalEnergyValue: number,
	windowHours: number,
) =>
	optimizeSchedule(tasks, windowHours, {
		...DEFAULT_ENERGY_PARAMS,
		freeTimeValue,
		terminalEnergyValue,
	}).blocks.reduce((sum, b) => (b.taskId === null ? sum : sum + b.hours), 0);

const worked = (freeTimeValue: number, terminalEnergyValue: number, windowHours: number) =>
	workedOn(DAY, freeTimeValue, terminalEnergyValue, windowHours);

describe('stopping-value identifiability', () => {
	it('sweeps V_T against λ₀ for the optimal stop (MATH.md §8.10 feasibility 2)', () => {
		const V_T = Array.from(
			{
				length: 13,
			},
			(_, i) => i * 0.5,
		);

		for (const windowHours of [8, 12]) {
			for (const lambda of [0.3, 0.5, 0.9, 1.3]) {
				const hours = V_T.map((vt) => worked(lambda, vt, windowHours));
				const levels = new Set(hours).size;

				console.log(
					`[§8.10 V_T] ${windowHours}h window, λ₀ ${lambda}: worked hours over V_T 0→6 ${hours.join('/')} — ${levels} distinct lattice level(s), span ${((Math.max(...hours) - Math.min(...hours)) / DEFAULT_STEP_HOURS).toFixed(0)} step(s)`,
				);
			}
		}
	});

	it('sweeps V_T over seeded days, so the span has a distribution (§8.10)', () => {
		const V_T = Array.from(
			{
				length: 13,
			},
			(_, i) => i * 0.5,
		);

		const rnd = mulberry32(810);
		const spans: number[] = [];
		let nonMonotone = 0;
		let atMostTwoLevels = 0;
		let worstSpan = 0;
		let worstDesc = '';

		for (let trial = 0; trial < 300; trial++) {
			const tasks = seededDay(rnd);
			const windowHours = 4 + Math.floor(rnd() * 11);
			const lambda = 0.1 + Math.floor(rnd() * 15) * 0.1;
			const hours = V_T.map((vt) => workedOn(tasks, lambda, vt, windowHours));
			const span = (Math.max(...hours) - Math.min(...hours)) / DEFAULT_STEP_HOURS;

			spans.push(span);

			if (new Set(hours).size <= 2) atMostTwoLevels++;

			if (hours.some((h, i) => i > 0 && h > hours[i - 1])) nonMonotone++;

			if (span > worstSpan) {
				worstSpan = span;
				worstDesc = `n=${tasks.length} T=${windowHours} λ₀=${lambda.toFixed(1)}: ${hours.join('/')}`;
			}
		}

		const sorted = [...spans].sort((x, y) => x - y);
		const at = (q: number) => sorted[Math.min(sorted.length - 1, Math.floor(q * sorted.length))];

		console.log(
			`[§8.10 V_T sweep] 300 seeded slider-reachable days, V_T over [0, 6] in 13 levels: ` +
				`span in 45-min steps median ${at(0.5)}, p90 ${at(0.9)}, worst ${worstSpan}; ` +
				`${atMostTwoLevels}/300 days at one or two levels; ${nonMonotone}/300 non-monotone in V_T`,
		);

		console.log(`[§8.10 V_T sweep] widest day — ${worstDesc}`);

		const moved = spans.filter((x) => x > 0).length;

		console.log(
			`[§8.10 V_T sweep] V_T moves the stop at all on ${moved}/300 days (a zero here would make the arm empty)`,
		);
	});

	it('tracks the true λ₀ through the bracket midpoint (MATH.md §8.10 reconstruction)', () => {
		for (const lambda of [0.5, 0.9, 1.3]) {
			const rows = [8, 10, 12].map((windowHours) => {
				const { blocks } = optimizeSchedule(DAY, windowHours, {
					...DEFAULT_ENERGY_PARAMS,
					freeTimeValue: lambda,
				});

				const logged = sessionRows(blocks);

				const point = (workedHours: StopObservation['workedHours']) => {
					const mid = stopIndifferencePoint(
						{
							tasks: DAY,
							windowHours,
							workedHours,
						},
						DEFAULT_ENERGY_PARAMS,
					);

					return mid === null ? 'censored' : mid.toFixed(3);
				};

				return `${windowHours}h ${point(logged)} (summed ${point(
					logged.map(({ taskId, hours }) => ({
						taskId,
						hours,
					})),
				)})`;
			});

			console.log(`[§8.10 midpoint] true λ₀ ${lambda}: ${rows.join(', ')}`);
		}
	});

	it('prices a mis-set V_T in λ₀, against the std printed beside it (§8.10)', () => {
		// The user's truth is the default V_T: their days are the plans at
		// (true λ₀, 1.5). Only the READER's slider moves, which is the error the
		// section calls "a real unfitted error source" — priced here in fit units.
		const TRUTH = DEFAULT_ENERGY_PARAMS.terminalEnergyValue;
		// The Energy Lab's own terminalEnergyValue range, so both ends are reachable.
		const MISSET = [0, 5];
		const rnd = mulberry32(824);

		for (const lambda of [0.5, 0.7, 0.9, 1.1]) {
			const days: StopObservation[] = [];

			for (let d = 0; d < 12; d++) {
				const tasks = seededDay(rnd);
				const windowHours = 4 + Math.floor(rnd() * 11);

				const { blocks } = optimizeSchedule(tasks, windowHours, {
					...DEFAULT_ENERGY_PARAMS,
					freeTimeValue: lambda,
					terminalEnergyValue: TRUTH,
				});

				days.push({
					tasks,
					windowHours,
					workedHours: sessionRows(blocks),
				});
			}

			const at = (terminalEnergyValue: number) =>
				fitStoppingValue(days, DEFAULT_ENERGY_PARAMS.freeTimeValue, {
					...DEFAULT_ENERGY_PARAMS,
					freeTimeValue: lambda,
					terminalEnergyValue,
				});

			const honest = at(TRUTH);

			if (!honest.fitted) {
				console.log(`[§8.10 V_T fit] true λ₀ ${lambda}: no day priced`);
				continue;
			}

			const read = MISSET.map((vt) => {
				const fit = at(vt);

				return `V_T ${vt} → λ̂₀ ${fit.value.toFixed(3)} ± ${fit.valueStd!.toFixed(3)} (n ${fit.usedCount}, shift ${Math.abs(fit.value - honest.value).toFixed(3)})`;
			});

			const worst = Math.max(...MISSET.map((vt) => Math.abs(at(vt).value - honest.value)));

			console.log(
				`[§8.10 V_T fit] true λ₀ ${lambda}: honest λ̂₀ ${honest.value.toFixed(3)} ± ${honest.valueStd!.toFixed(3)} (n ${honest.usedCount}) — ` +
					`${read.join(', ')}; worst shift ${(worst / honest.valueStd!).toFixed(1)}× the std it prints`,
			);
		}
	});
});
